apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-n7rh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zfyv-tenant/rhtap-demo-app/hacbs-test-project-n7rh@sha256:94341a2ecc64a85e7bc7cc5a199b974e3f33f99f248cdaa2f5680b773153f401
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
