apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-n7rh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-n7rh
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-n7rh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-n7rh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-n7rh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zfyv-tenant/rhtap-demo-app/hacbs-test-project-n7rh@sha256:94341a2ecc64a85e7bc7cc5a199b974e3f33f99f248cdaa2f5680b773153f401
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
